<?php

// Partners

return [
    [
        "title"        => "Petersburg2",
        "slug"         => "petersburg",
        "category"     => "Спонсоры",
        "link"         => "http://peterburg2.ru/",
        "meta"         => ['width' => '115', 'height' => '40'],
        "published"    => 1,
    ],
    [
        "title"        => "Эксперимент",
        "slug"         => "eksperiment",
        "category"     => "Спонсоры",
        "link"         => "http://md-eksperiment.org/",
        "meta"         => ['width' => '78', 'height' => '47'],
        "published"    => 1,
    ],
    [
        "title"        => "Конкретно",
        "slug"         => "konkretno",
        "category"     => "Спонсоры",
        "link"         => "http://konkretno.ru/",
        "meta"         => ['width' => '132', 'height' => '29'],
        "published"    => 1,
    ],
    [
        "title"        => "Зеркало",
        "slug"         => "zerkalo",
        "category"     => "Спонсоры",
        "link"         => "http://www.zerkalospb.ru/",
        "meta"         => ['width' => '81', 'height' => '36'],
        "published"    => 1,
    ],
    [
        "title"        => "Около",
        "slug"         => "okolo",
        "category"     => "Спонсоры",
        "link"         => "http://okolo.me/",
        "meta"         => ['width' => '88', 'height' => '47'],
        "published"    => 1,
    ],
    [
        "title"        => "AVIMedia",
        "slug"         => "avimedia",
        "category"     => "Спонсоры",
        "link"         => "http://avi-media.ru/",
        "meta"         => ['width' => '78', 'height' => '42'],
        "published"    => 1,
    ],
    [
        "title"        => "Ok-inform",
        "slug"         => "okinform",
        "category"     => "Спонсоры",
        "link"         => "http://ok-inform.ru/",
        "meta"         => ['width' => '116', 'height' => '29'],
        "published"    => 1,
    ],
    [
        "title"        => "KronNews",
        "slug"         => "kronnews",
        "category"     => "Спонсоры",
        "link"         => "http://kronnews.ru/",
        "meta"         => ['width' => '87', 'height' => '44'],
        "published"    => 1,
    ],
    [
        "title"        => "KudaGo",
        "slug"         => "kudago",
        "category"     => "Спонсоры",
        "link"         => "http://kudago.com/",
        "meta"         => ['width' => '128', 'height' => '56'],
        "published"    => 1,
    ],
    [
        "title"        => "Теледом",
        "slug"         => "teledom",
        "category"     => "Спонсоры",
        "link"         => "http://teledom.tv/",
        "meta"         => ['width' => '122', 'height' => '26'],
        "published"    => 1,
    ],
    [
        "title"        => "ПанорамаТВ",
        "slug"         => "panorama",
        "category"     => "Спонсоры",
        "link"         => "http://panorama-tv.ru/",
        "meta"         => ['width' => '', 'height' => ''],
        "published"    => 0,
    ],
    [
        "title"        => "PiterStory",
        "slug"         => "piterstory",
        "category"     => "Спонсоры",
        "link"         => "http://piterstory.com/",
        "meta"         => ['width' => '', 'height' => ''],
        "published"    => 0,
    ],



    [
        "title"        => "МузБилет",
        "slug"         => "muzbilet",
        "category"     => "Партнеры",
        "link"         => "http://muzbilet.ru/",
        "meta"         => ['width' => '135', 'height' => '42'],
        "published"    => 1,
    ],
    [
        "title"        => "СубКультура",
        "slug"         => "subkultura",
        "category"     => "Партнеры",
        "link"         => "http://sub-cult.ru/",
        "meta"         => ['width' => '125', 'height' => '37'],
        "published"    => 1,
    ],
    [
        "title"        => "Кассир",
        "slug"         => "kassir",
        "category"     => "Партнеры",
        "link"         => "https://www.kassir.ru/",
        "meta"         => ['width' => '125', 'height' => '49'],
        "published"    => 1,
    ],
    [
        "title"        => "Билетер",
        "slug"         => "bileter",
        "category"     => "Партнеры",
        "link"         => "http://www.bileter.ru/",
        "meta"         => ['width' => '150', 'height' => '39'],
        "published"    => 1,
    ],
    [
        "title"        => "БилетСофит",
        "slug"         => "biletsofit",
        "category"     => "Партнеры",
        "link"         => "http://www.biletsofit.ru/",
        "meta"         => ['width' => '156', 'height' => '47'],
        "published"    => 1,
    ],
    [
        "title"        => "Oyster Telecom",
        "slug"         => "oyster",
        "category"     => "Партнеры",
        "link"         => "http://www.oyster-telecom.ru/",
        "meta"         => ['width' => '175', 'height' => '70'],
        "published"    => 1,
    ],
    [
        "title"        => "Буквоед",
        "slug"         => "bukvoed",
        "category"     => "Партнеры",
        "link"         => "http://www.bookvoed.ru/",
        "meta"         => ['width' => '138', 'height' => '43'],
        "published"    => 1,
    ],

];